---
version: "3"
services:
  rtkskit:
    build: .
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - GLPI_BASE_URL=${GLPI_BASE_URL}
      # Uncomment bellow to provide non-default values
      # - GLPI_APP_API_KEY=${GLPI_APP_API_KEY}
      # - CHECK_PERIOD=${CHECK_PERIOD}
      # - LOG_LEVEL=${LOG_LEVEL}

    # Uncomment bellow to save state between container restart:
    # volumes:
    #   - ./telegram-bot:/data
