---
version: "3"
services:
  rtkskit:
    build: .
    restart: unless-stopped
#    environment:
#      - TELEGRAM_TOKEN:"TO_REPLACE"
#      - GLPI_BASE_URL:"http://TO_REPLACE/apirest.php/"
#    volumes:
#        - /TO_REPLACE:/data
