---
version: "3"
services:
  rtkskit:
    build: .
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN:${TELEGRAM_TOKEN}
      - GLPI_BASE_URL:${GLPI_BASE_URL}
#    volumes:
#        - /TO_REPLACE:/data
